services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  smtp:
    build:
      context: .
      dockerfile: Dockerfile.smtp
    restart: unless-stopped
    ports:
      - "25:25"
    environment:
      - SMTP_PORT=25
      - SMTP_HOST=0.0.0.0
      - SMTP_DOMAIN=${SMTP_DOMAIN:-localhost}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_PATH=/app/data
    volumes:
      - db_data:/app/data
    depends_on:
      redis:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SMTP_DOMAIN=${SMTP_DOMAIN:-localhost}
      - DB_PATH=/app/data
    volumes:
      - db_data:/app/data
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data:
  db_data:


