services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    #ports:
    #  - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      -  junkmail_default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  smtp:
    build:
      context: .
      dockerfile: Dockerfile.smtp
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - "25:25"
    volumes:
      - db_data:/app/data
    networks:
      - junkmail_default
      - reverse-proxy_default
    depends_on:
      redis:
        condition: service_healthy

  junkmail:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.prod
    #ports:
      #- "3000:80"
    volumes:
      - db_data:/app/data
    networks:
      - junkmail_default
      - reverse-proxy_default
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data:
  db_data:

networks:
  junkmail_default:
  reverse-proxy_default:
    external: true
